COLORS:
  - "#1f77b4"
  - "#ff7f0e"
  - "#2ca02c"
  - "#d62728"
  - "#9467bd"
  - "#612b20"
  - "#e377c2"
  - "#7f7f7f"
  - "#bcbd22"
  - "#17becf"
  - "#A6761D"
  - "#ffbb78"
  - "#98df8a"
  - "#393b79"