# configs/param_config.yaml

parameters:
  # -------------------------
  # Operating conditions
  # -------------------------
  - name: Tfc                 # Cell temperature (K)
    type: continuous
    low: 333
    high: 363
    fixed: false

  - name: Pa_des              # Desired cell pressure (Pa)
    type: continuous
    low: 130000.0
    high: 300000.0
    fixed: false

  - name: Pc_des              # Cathode pressure (Pa) = Pa_des - 20000
    type: continuous
    derived: "Pa_des - 20000"   # computed from Pa_des — no manual edit needed
    fixed: true                  # value is computed at runtime

  - name: Sc                  # Stoichiometry anode
    type: continuous
    low: 1.1
    high: 3.0
    fixed: false

  - name: Sa                  # Stoichiometry cathode 
    type: continuous
    value: 1.3
    fixed: true

  - name: Phi_c_des          # Entrance humidity anode 
    type: continuous
    low: 0.1
    high: 0.7
    fixed: false

  - name: Phi_a_des          # Anode humidity 
    type: continuous
    value: 0.5
    fixed: true

  # -------------------------------------
  # Undetermined physical parameters
  # -------------------------------------
  - name: epsilon_gdl        # GDL porosity
    type: continuous
    low: 0.55
    high: 0.8
    fixed: false

  - name: tau                # Pore structure coefficient
    type: continuous
    low: 1.0
    high: 4.0
    fixed: false

  - name: epsilon_mc         # CL ionomer volume fraction
    type: continuous
    low: 0.15
    high: 0.4
    fixed: false

  - name: epsilon_c          # GDL compression ratio
    type: continuous
    low: 0.15
    high: 0.3
    fixed: false

  - name: e                  # Capillary exponent (discrete!)
    type: integer
    low: 3
    high: 5
    fixed: false
    # We could also try to do {3,4,5} -> switch to categorical
    # type: categorical
    # values: [3, 4, 5]

  - name: Re                 # Electron conduction resistance (Ω·m²)
    type: continuous
    low: 5.0e-7
    high: 5.0e-6
    fixed: false

  - name: i0_c_ref           # Cathode exchange current density (A/m²)
    type: continuous
    low: 0.001
    high: 80
    fixed: false

  - name: kappa_co           # Crossover correction coefficient (mol/(m·s·Pa))
    type: continuous
    low: 15
    high: 40
    fixed: false

  - name: kappa_c            # Overpotential correction exponent
    type: continuous
    low: 0
    high: 2.5
    fixed: false

  - name: a_slim
    type: continuous
    value: 0
    fixed: true

  - name: b_slim
    type: continuous
    value: 1
    fixed: true

  - name: a_switch
    type: continuous
    value: 0.99
    fixed: true